version: '3.3'

volumes:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: spookyviking/foodgram:latest
    command: >
      sh -c "python manage.py makemigrations users &&
             python manage.py makemigrations recipes &&
             python manage.py makemigrations core &&
             python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn foodgram.wsgi:application --bind 0:8000"
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: spookyviking/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend